DATA SEGMENT
    ARRAY     DW 0005H, 0FFF0H, 0003H, 0FFFEH, 0007H
    COUNT     DW 05H
    POS_ARRAY DW 5 DUP(?)
    NEG_ARRAY DW 5 DUP(?)
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX

    LEA SI, ARRAY
    LEA DI, POS_ARRAY
    LEA BP, NEG_ARRAY
    MOV CX, COUNT

LOOP1:
    MOV AX, [SI]
    TEST AX, 8000H
    JZ POSITIVE
    
    MOV [BP], AX
    ADD BP, 2
    JMP NEXT_NUM

POSITIVE:
    MOV [DI], AX
    ADD DI, 2
    
NEXT_NUM:
    ADD SI, 2
    DEC CX
    JNZ LOOP1

    MOV AH, 4CH
    INT 21H
CODE ENDS
END START